name: Tpj
version: '${project.version}'
main: enderlava.tpj.Tpj
api-version: 1.19
authors: [ Enderlava ]
description: An player tp plugin
website: https://github.com/lava114514/Tpj

commands:
  tpj:
    description: Teleport between players
    usage: /tpj <player>
  tpjaccept:
    description: Accept teleport request
    usage: /tpjaccept
    aliases: [y,tpyes]
  tpjhelp:
    description: tpj description
    usage: /tpjhelp